name: Trigger Pipe Manager

on:
  push:
    branches:
      - master

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pipe Manager Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: mnoskoski/pipe-manager
          token: ${{ secrets.github  }}
          event-type: trigger-ci
      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute tests with pytest
        run: pytest
