name: Trigger Pipe Manager

on:
  push:
    branches:
      - master

jobs:
  trigger-pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pipe Manager Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: mnoskoski/pipe-manager
          token: ${{ secrets.github  }}
          event-type: trigger-ci
